[module.hugoVersion]
extended = true

[[module.imports]]
path = "github.com/hugomods/icons/vendors/bootstrap"

[params.hugopress.modules.debugger.hooks.head-begin]
weight = 1

[params.hugopress.modules.debugger.hooks.body-end]

[params.debugger]
